### ISSUE TITLE
Quantopian is closed

### ISSUE THREAD

**Issue by Molozey** [PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading#12]
Could u please name an analog to make backtests. Now I'm looking at Quantconnect, but i'm not sure that's this is good alternative

**Comment by marvin-hansen** [comment]
@Molozey Forget about Quantconnect, it's broken. I used to work with it for ~3 months but ultimately had to give up because they could not run my system on their servers and their CEO refused to fix a couple of issues I brought up and were forwarded to him. Make out of that whateer you want

Feasible alternatives:

https://www.quantrocket.com/ 

https://tickblaze.com/ 

Tickblaze (formerly known as QuantTerminal) is amazing, perhaps the closest you can get to actually useful. 

If you look for systematic trading system that actually works in practice, give unger academy a try. I did it, it works extremely well, and I got my current position as head of quant research because of it... Just saying. 

https://ungeracademy.com/about

**Comment by Molozey** [comment]
@marvin-hansen OMG, thank's for your so fast answer. I really appreciate it. I'll try to figure out the resources you specified

**Comment by deepesh-packt** [comment]
Hello! Please reopen if the issue still persists.
